plugins:
  - jekyll-remote-theme
remote_theme: ngzhio/jekyll-theme-hamilton
skin: midnight
google_analytics: G-VXFCGE9Q4G
avatar: icon.svg
author: [Paulo Roberto Elias](https://paulorobertoelias.com.br)
