plugins:
  - jekyll-remote-theme
  - jekyll-feed
remote_theme: ngzhio/jekyll-theme-hamilton
skin: midnight
google_analytics: G-VXFCGE9Q4G
avatar: icon.svg
author: Paulo Roberto Elias and Marcos Alves
excerpt_separator: <!--more-->
